esphome:
  name: basement-north

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

logger:

wifi:
  ssid: Maker Space
  password: ""

web_server:

prometheus:

i2c:
  sda: GPIO32
  scl: GPIO33
  scan: true

uart:
  id: pm_uart
  tx_pin: GPIO21
  rx_pin: GPIO19
  baud_rate: 9600

sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: "North Basement Temperature"
    humidity:
      name: "North Basement Humidity"
    update_interval: 60s

  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "North Basement PM1 Concentration"
    pm_2_5:
      name: "North Basement PM2.5 Concentration"
    pm_10_0:
      name: "North Basement PM10 Concentration"
    uart_id: pm_uart
    update_interval: 60s
