esphome:
  name: comms-room

esp32:
  board: esp32-poe
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO17
    mode: CLK_OUT
  phy_addr: 0
  power_pin: GPIO12

logger:

web_server:

prometheus:

one_wire:
  - platform: gpio
    pin: GPIO13

sensor:
  - platform: dallas_temp
    address: 0xd63ce1e380a63428
    name: board_temperature
    update_interval: 60s

  - platform: dallas_temp
    address: 0x953c1ff648a2f028
    name: temperature_1
    update_interval: 60s

  - platform: dallas_temp
    address: 0x0d3ce1e3817d8828
    name: temperature_2
    update_interval: 60s
