esphome:
  name: main-workshop

  on_boot:
    - priority: -100
      then:
        - senseair.abc_enable: co2

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

logger:

wifi:
  ssid: Maker Space
  password: ""

http_request:

i2c:
  sda: GPIO32
  scl: GPIO33
  scan: true

uart:
  id: co2_uart
  tx_pin: GPIO21
  rx_pin: GPIO19
  baud_rate: 9600

sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: Temperature
      on_value:
        then:
          - http_request.post:
              url: "https://environment-sensor:PASSWORD@telemetry.makerspace.org.uk/environment-sensor"
              body: !lambda |-
                return ((std::string) "temperature{node=\"main-workshop\"} " + to_string(x) + "\n").c_str();
    humidity:
      name: Humidity
      on_value:
        then:
          - http_request.post:
              url: "https://environment-sensor:PASSWORD@telemetry.makerspace.org.uk/environment-sensor"
              body: !lambda |-
                return ((std::string) "humidity{node=\"main-workshop\"} " + to_string(x) + "\n").c_str();
    update_interval: 60s

  - platform: senseair
    id: co2
    uart_id: co2_uart
    co2:
      name: co2
      on_value:
        then:
          - http_request.post:
              url: "https://environment-sensor:PASSWORD@telemetry.makerspace.org.uk/environment-sensor"
              body: !lambda |-
                return ((std::string) "co2{node=\"main-workshop\"} " + to_string(x) + "\n").c_str();
